language: rust

sudo: false

notifications:
    email: false

branches:
    only: master

script:
    - cargo build --verbose
    - cargo test  --verbose
    - cargo build --verbose --features 'serde serde_derive'
    - cargo test  --verbose --features 'serde serde_derive'

after_success: |
    [ $TRAVIS_BRANCH = master ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    cargo doc --features serde &&
    echo '<meta http-equiv=refresh content=0;url=ketos/index.html>' > target/doc/index.html &&
    pip install --user ghp-import &&
    ghp-import -n target/doc &&
    git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
