language: rust

sudo: false

notifications:
    email: false

branches:
    only: master

script:
    - cargo build --verbose
    - cargo test  --verbose
    - cargo build --verbose --features 'serde serde_derive'
    - cargo test  --verbose --features 'serde serde_derive'
    - ( cd ketos_derive && cargo build --verbose )
    - ( cd ketos_derive && cargo test  --verbose )
