[package]
name = "ketos"
description = "Lisp dialect scripting and extension language"

documentation = "http://murarth.github.io/ketos/ketos/index.html"
homepage = "https://github.com/murarth/ketos"
repository = "https://github.com/murarth/ketos"

keywords = [ "scripting", "extension", "functional", "language", "lisp" ]
license = "MIT/Apache-2.0"
readme = "README.md"

version = "0.2.2"
authors = ["Murarth <murarth@gmail.com>"]

[[bin]]
name = "ketos"
path = "src/bin/repl.rs"
doc = false

[lib]
name = "ketos"
path = "src/ketos/lib.rs"

[dependencies]
byteorder = "0.5.1"
getopts = "0.2"
linefeed = "0.1"
num = "0.1.32"
rand = "0.3"
serde = "0.7"

[dev-dependencies]
assert_matches = "1.0"
